# Generated by Django 5.2 on 2025-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('suspeito', 'Suspeito'), ('confirmado', 'Confirmado'), ('negativado', 'Negativado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='symptoms',
            field=models.ManyToManyField(blank=True, through='dengue_tracker_app.CaseSymptom', to='dengue_tracker_app.symptom'),
        ),
    ]
