# Generated by Django 5.2 on 2025-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue_tracker_app', '0002_alter_case_status_alter_case_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
